version: '3'

# TODO ckb health check before starting ckb-miner
# TODO ckb health check: RPC started
# TODO ckb-miner health check: 出够 15 个块
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lumos
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/web3-indexer-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis:bullseye
    user: redis:redis
    ports: 
      - 6379:6379
    volumes:
      - ./redis/data:/data

  ckb:
    image: nervos/ckb:v0.101.4
    environment:
      CKB_CHAIN: devnet
    ports:
      - "8114:8114"   # rpc
      - "18114:18114" # subscription
      - "8115:8115"   # network
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ "run", "-C", "/var/lib/ckb" ]

  ckb-miner:
    image: nervos/ckb:v0.101.4
    environment:
      CKB_CHAIN: devnet
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ "miner", "-C", "/var/lib/ckb" ]
    depends_on:
      - ckb

  ckb-indexer:
    image: nervos/ckb-indexer:0.3.2
    environment:
      CKB_RPC: http://ckb:8114
    ports:
      - "8116:8116"   # ckb-indexer rpc
    volumes:
      - ./ckb-indexer:/var/lib/ckb-indexer
    command: [ "-c", "http://ckb:8114", "-l", "0.0.0.0:8116", "-s", "/var/lib/ckb-indexer" ]
    depends_on:
      - ckb

  # This short-term service is used to deploy layer1 scripts and output the
  # deployment information into "scripts-deployment.json" file.
  #
  # All the scripts were compiled and [packaged into "nervos/godwoken-prebuilds" image](https://github.com/nervosnetwork/godwoken-docker-prebuilds/blob/97729b15093af6e5f002b46a74c549fcc8c28394/Dockerfile#L42-L54)
  deploy_scripts:
    image: nervos/godwoken-prebuilds:v0.10.2
    volumes:
      - ./godwoken:/var/lib/godwoken
      - ./share:/var/lib/share
    command:
      - "gw-tools"
      - "deploy-scripts"
      - "--ckb-rpc"
      - "http://ckb:8114"
      - "-i"
      - "/var/lib/godwoken/scripts-config.json"
      - "-o"
      - "/var/lib/godwoken/scripts-deployment.json"
      - "-k"
      - "/var/lib/share/test_only_privkey_of_block_assembler"
    restart: "no"
    depends_on:
      - ckb
      - ckb-miner
