version: '3'

# TODO CKB health check before starting ckb-miner
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lumos
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/web3-indexer-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis:bullseye
    user: redis:redis
    ports: 
      - 6379:6379
    volumes:
      - ./redis/data:/data

  ckb:
    image: nervos/ckb:v0.101.4
    environment:
      CKB_CHAIN: devnet
    ports:
      - "8114:8114"   # rpc
      - "18114:18114" # subscription
      - "8115:8115"   # network
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ "run", "-C", "/var/lib/ckb" ]

  ckb-miner:
    image: nervos/ckb:v0.101.4
    environment:
      CKB_CHAIN: devnet
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ "miner", "-C", "/var/lib/ckb" ]
    depends_on:
      - ckb
