version: '3'

# TODO ckb-miner health check: block number is greater than 20
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lumos
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/web3-indexer-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis:bullseye
    user: redis:redis
    ports: 
      - 6379:6379
    volumes:
      - ./redis/data:/data

  ckb:
    image: nervos/ckb:v0.101.4
    environment:
      CKB_CHAIN: devnet
    ports:
      - "8114:8114"   # rpc
      - "18114:18114" # subscription
      - "8115:8115"   # network
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ "run", "-C", "/var/lib/ckb" ]

  # "nervos/ckb" image have no http clients to do health check for CKB.
  # ckb-health-check act as a workaround to do health check.
  ckb-health-check:
    image: nervos/godwoken-prebuilds:v0.10.2
    volumes:
      - ./ckb:/var/lib/ckb
    entrypoint: /var/lib/ckb/ckb-health-check.sh

  ckb-miner:
    image: nervos/ckb:v0.101.4
    environment:
      CKB_CHAIN: devnet
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ "miner", "-C", "/var/lib/ckb" ]

  ckb-indexer:
    image: nervos/ckb-indexer:0.3.2
    environment:
      CKB_RPC: http://ckb:8114
    ports:
      - "8116:8116"   # ckb-indexer rpc
    volumes:
      - ./ckb-indexer:/var/lib/ckb-indexer
    command: [ "-c", "http://ckb:8114", "-l", "0.0.0.0:8116", "-s", "/var/lib/ckb-indexer" ]
    depends_on:
      ckb-health-check:
        condition: service_completed_successfully

  # This short-term service is used to deploy layer1 scripts and output the
  # deployment information into "scripts-deployment.json" file.
  #
  # All the scripts were compiled and [packaged into "nervos/godwoken-prebuilds" image](https://github.com/nervosnetwork/godwoken-docker-prebuilds/blob/97729b15093af6e5f002b46a74c549fcc8c28394/Dockerfile#L42-L54)
  deploy-scripts:
    image: nervos/godwoken-prebuilds:v0.10.2
    volumes:
      - ./godwoken:/var/lib/godwoken
    entrypoint: /var/lib/godwoken/deploy-scripts.sh
    restart: "no"
    depends_on:
      - ckb
      - ckb-miner

  # This short-term service generate rollup-config.json
  generate-rollup-config:
    image: nervos/godwoken-prebuilds:v0.10.2
    volumes:
      - ./godwoken:/var/lib/godwoken
    entrypoint: /var/lib/godwoken/generate-rollup-config.sh
    restart: "no"
    depends_on:
      deploy-scripts:
        condition: service_completed_successfully
      ckb:
        condition: service_started

  # This short-term service deploys rollup's genesis cell
  deploy-rollup-genesis:
    image: nervos/godwoken-prebuilds:v0.10.2
    volumes:
      - ./godwoken:/var/lib/godwoken
    entrypoint: /var/lib/godwoken/deploy-rollup-genesis.sh
    restart: "no"
    depends_on:
      generate-rollup-config:
        condition: service_completed_successfully
      ckb:
        condition: service_started
      ckb-indexer:
        condition: service_started

  generate-godwoken-config:
    image: nervos/godwoken-prebuilds:v0.10.2
    volumes:
      - ./godwoken:/var/lib/godwoken
    entrypoint: /var/lib/godwoken/generate-godwoken-config.sh
    restart: "no"
    depends_on:
      deploy-rollup-genesis:
        condition: service_completed_successfully

  godwoken:
    image: nervos/godwoken-prebuilds:v0.10.2
    ports:
      - 8119:8119
      - 8120:8120
    volumes:
      - ./godwoken:/var/lib/godwoken
    depends_on:
      ckb-health-check:
        condition: service_completed_successfully
      generate-godwoken-config:
        condition: service_completed_successfully
    command: [ "godwoken", "run", "-c", "/var/lib/godwoken/godwoken-config.toml" ]
